CREATE DATABASE pee
  WITH ENCODING='UTF8'
       CONNECTION LIMIT=-1;

CREATE TABLE produtos (idProdutos SERIAL PRIMARY KEY NOT NULL,
    nome VARCHAR(50) NOT NULL,
    descricao VARCHAR(254) NOT NULL,
    valor FLOAT NOT NULL
);
